[features]
seeds = false
[programs.devnet]
staking = "prf15pWWefyM69ytYc5AS2wWfRYJCU8kAikKRTQBTvT"
[programs.mainnet]
staking = "HeQTtHWw83MhXGQXgWdQdFKbwhRuNDyRcTo648WsXHnT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tomekregulski/desktop/magnum_ai/trash/staking-deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
